apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
      - name: app
        image: yourrepo/poc-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets